package com.outsera.goldenraspberry.repository;

import com.outsera.goldenraspberry.model.Movie;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * Repository interface for Movie entity.
 * <p>
 * Provides CRUD operations and custom queries for Movie data.
 * Spring Data JPA automatically generates the implementation.
 * </p>
 */
@Repository
public interface MovieRepository extends JpaRepository<Movie, Long> {

    /**
     * Find all movies where winner is true.
     * <p>
     * Query method automatically generated by Spring Data JPA
     * from the method name convention.
     * </p>
     *
     * @return List of winning movies
     */
    List<Movie> findByWinnerTrue();

}
